FORMAT: 1A
HOST: https://v1.api.dudesolutions.io

USECOMMONSDKLIBRARY: TRUE
GENERATEASYNCCODE: TRUE
GENERATEINTERFACES: TRUE
USEMETHODPREFIX: TRUE
USEMODELPOSTFIX: FALSE
USECONTROLLERPOSTFIX: FALSE
USEENUMPOSTFIX: FALSE
USECONSTRUCTORSFORCONFIG: TRUE
CSHARPDEFAULTNAMESPACE: DSI.SDK.Inventory
JAVADEFAULTNAMESPACE: io.dudesolutions.inventory
BRANDLABEL: Dude Solutions, Inc.
USERAGENT: Dude SDK
NULLIFY404: TRUE
VALIDATEREQUIREDPARAMETERS: FALSE
COLLECTPARAMETERS: TRUE

# Dude Inventory Api

## Reference
Good reference document: https://raw.githubusercontent.com/apiaryio/api-blueprint/master/examples/Polls%20API.md

## Authentication
Inventory Api uses OAuth v2 Authorization. First you create a new (or acquire existing) OAuth v2 token using [DudeAuth](https://www.dudeauth.com/).

## Media Types
Where applicable this API uses the *JSON* media-type to represent resources.

Requests and responses with a message-body use plain JSON to set or update resources.

## Error States
The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used throughout this API.

In addition to standard response codes the response object returned from the server during an exception event may contain additional information in the following JSON format:

        {
            "message": "SOME MESSAGE",
            "dudeReferenceId": "3523845A-4729-4CCB-9E16-01DEADF6C2DF",
            "stackTrace": "Null, Typically"
        }

# Group System Information

## System Information [/]

### GET

+ Response 200 (application/json; charset=utf-8)
    + Attributes (System Information)

# Group Heartbeat

## Heartbeat [/heartbeat]
The heartbeat is exposed and provided to check for availability of the service.
Any response that does not provide a ```200 OK``` response code should be treated as an error.

### GET

+ Response 200 (application/json; charset=utf-8)
    + Headers

            X-Dude-Api-Limit: Unlimited or Number
            X-Dude-Api-Remaining: Unlimited or Number
            X-Dude-Api-Server: Api Server ID

    + Attributes (Heartbeat)


# Group Inventory Item

## Inventory Item Collection [/accounts/{accountId}/inventoryitems{?page,pagesize,orderby}]

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
    + page: 1 (number, optional) - {INT} The page to request from the collection.
    + pagesize: 1000 (number, optional) - {INT} The number of records to load in a page from the collection.
    + orderby: Id desc (string, optional) - A string describing the ordering to perform on the collection.

### GET

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Base Collection Response)
        + `data` (array[Inventory Item Update], required)

### POST

+ Request
    + Attributes (Inventory Item Data)

+ Response 201 (application/json; charset=utf-8)
    + Attributes (Inventory Item Update)

## Inventory Item Detail [/accounts/{accountId}/inventoryitems/{id}]

+ Parameters
    + accountId: 2 (number, required) - {INT} ID of the account in the form of an integer
    + id: 1 (number, required) - {INT} The ID of the Inventory Item

### GET

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Inventory Item Update)

### PUT

+ Request
    + Attributes (Inventory Item Update)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Inventory Item Data)

### DELETE

+ Response 204 (application/json; charset=utf-8)

# Data Structures

## System Information (object)
+ `application`: `Dude Inventory Api` (string, required) - The name of the application.
+ `version` : `1.0.0.0` (string, required) - The assembly version.
+ `apiVersion` : `1.0.0.0` (string, required) - The API version.
+ `vitals` (Heartbeat, required) - The state of the system dependencies.
+ `links` (array[System Links], required) - The API routes.

## System Links (object)
+ `endpoint` : `Inventory` (string, required) - The name of the endpoint.
+ `action` : `Get` (string, required) - The REST action.
+ `route` : `/accounts/{accountId}/inventoryitems` (string, required) - The route to the endpoint.

## Heartbeat (object)
+ `cachevitalcheck`: true (boolean, required) - Vital check to ensure cache is available and online
+ `inventorydbvitalcheck`: true (boolean, required) - Vital check to ensure database is online.

## Base Collection Response (object)
+ `page`: 1 (number, required) - {INT} The current page provided in the response data.
+ `pageSize`: 1000 (number, required) - {INT} The page size returned in the response data.
+ `dataSize` (number, required) - {INT} The total records returned in the response.
+ `total` (number, required) - {INT} The total number of records available in the collection.

## Inventory Item Data
+ `internalIdentifier`: `P/N 234234A` (string, required) - The unique identifier of the inventory item as defined by customer
+ `description`: `Rectifier Avalanche Diode` (string, optional) - Description of the inventory item
+ `isActive`: true (boolean, required) - Indicates if the inventory item is active

## Inventory Item Update (Inventory Item Data)
+ `id`: 1234567890 (number, required) - {INT} The ID for the object